INSERT INTO
    users (
        user_id,
        first_name,
        middle_name,
        last_name,
        email,
        hashed_password,
        phone
    )
VALUES
    (
        1,
        'john',
        'middle',
        'smith',
        'js@gmail.com',
        'asdhdsak13231213',
        2245555555
    ),
    (
        2,
        'jeff',
        'mid',
        'brown',
        'jb@gmail.com',
        'dsadas54145',
        2245555556
    ),
    (
        3,
        'jared',
        'm',
        'leto',
        'jl@gmail.com',
        'fgfsd451',
        2245555557
    )